# Generated by Django 4.0 on 2023-12-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0002_schedule_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='added_by',
            new_name='added',
        ),
    ]
