# Generated by Django 4.0 on 2023-12-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0003_rename_added_by_schedule_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='added',
        ),
    ]
