# Generated by Django 4.0 on 2023-12-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0005_schedule_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='added',
        ),
    ]
