# Generated by Django 4.0 on 2023-12-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0007_schedule_brgy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='brgy',
        ),
    ]
