# Generated by Django 4.0 on 2023-12-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0009_schedule_brgy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='vax',
        ),
        migrations.AddField(
            model_name='schedule',
            name='vax',
            field=models.ManyToManyField(to='vaxapp.Vaccine'),
        ),
    ]
