# Generated by Django 4.0 on 2023-12-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0010_remove_schedule_vax_schedule_vax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='vax',
        ),
        migrations.AddField(
            model_name='schedule',
            name='vax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaxapp.vaccine'),
        ),
    ]
