# Generated by Django 4.0 on 2023-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0011_remove_schedule_vax_schedule_vax'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brgy_address', models.ManyToManyField(to='vaxapp.Barangay')),
            ],
        ),
    ]
