# Generated by Django 4.0 on 2023-12-06 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaxapp', '0012_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='user_name',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
