# Generated by Django 4.0 on 2023-12-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vaxapp', '0013_user_address_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='brgy_address',
        ),
        migrations.AddField(
            model_name='user_address',
            name='brgy_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.barangay'),
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user_address',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
