# Generated by Django 4.0 on 2023-12-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0014_remove_user_address_brgy_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_address',
        ),
    ]
