# Generated by Django 4.0 on 2023-12-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vaxapp', '0015_delete_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='guardian',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
