# Generated by Django 4.0 on 2023-12-06 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0016_schedule_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
