# Generated by Django 4.0 on 2023-12-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0019_remove_schedule_vax'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='vaccine_record',
            field=models.JSONField(default=None),
        ),
    ]
