# Generated by Django 4.0 on 2023-12-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0020_register_vaccine_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='vaccine_record',
        ),
    ]
