# Generated by Django 4.0 on 2023-12-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0022_vaccine_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='vaccine_info',
            field=models.TextField(default=None),
        ),
    ]
