# Generated by Django 4.0 on 2023-12-07 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0023_alter_vaccine_record_vaccine_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.register'),
        ),
    ]
