# Generated by Django 4.0 on 2023-12-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0024_alter_vaccine_record_child'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
