# Generated by Django 4.0 on 2023-12-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0028_alter_barangay_healthworker_alter_register_added_by_and_more'),
    ]

    operations = [
    ]
