# Generated by Django 4.0 on 2023-12-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0030_auto_20231209_0039'),
    ]

    operations = [
    ]
