# Generated by Django 4.0 on 2023-12-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0031_auto_20231209_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='brgy',
            new_name='brgyId',
        ),
    ]
