# Generated by Django 4.0 on 2023-12-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0033_rename_brgyid_schedule_brgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine_record',
            name='vaccine_id',
            field=models.IntegerField(null=True),
        ),
    ]
