# Generated by Django 4.0 on 2023-12-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0034_vaccine_record_vaccine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
