# Generated by Django 4.0 on 2023-12-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0037_vaccine_record_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='vaccination_date',
            field=models.DateTimeField(default=None),
        ),
    ]
