# Generated by Django 4.0 on 2023-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0038_alter_vaccine_record_vaccination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='vaccination_date',
            field=models.TextField(),
        ),
    ]
