# Generated by Django 4.0 on 2023-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0043_rename_vax1_vaccine_record_vaccine_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine_record',
            old_name='vaccine_id',
            new_name='vax1',
        ),
        migrations.RenameField(
            model_name='vaccine_record',
            old_name='vaccine_info',
            new_name='vax1_info',
        ),
        migrations.AddField(
            model_name='vaccine_record',
            name='vax2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaccine_record',
            name='vax2_info',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='vaccine_record',
            name='vax3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaccine_record',
            name='vax3_info',
            field=models.TextField(default=None),
        ),
    ]
