# Generated by Django 4.0 on 2023-12-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0044_rename_vaccine_id_vaccine_record_vax1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='vaccine_info',
            new_name='vax1_info',
        ),
        migrations.AddField(
            model_name='schedule',
            name='vax1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vax2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vax2_info',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vax3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vax3_info',
            field=models.TextField(default=None),
        ),
    ]
