# Generated by Django 4.0 on 2023-12-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0045_rename_vaccine_info_schedule_vax1_info_schedule_vax1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='vax1_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vax2_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vax3_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax1_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax2_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax3_info',
            field=models.TextField(null=True),
        ),
    ]
