# Generated by Django 4.0 on 2023-12-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0046_alter_schedule_vax1_info_alter_schedule_vax2_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vaccine_record',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
