# Generated by Django 4.0 on 2023-12-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0048_alter_schedule_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
