# Generated by Django 4.0 on 2023-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0049_alter_vaccine_record_vax1_alter_vaccine_record_vax2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax3',
            field=models.IntegerField(null=True),
        ),
    ]
