# Generated by Django 4.0 on 2023-12-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0050_alter_vaccine_record_vax1_alter_vaccine_record_vax2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaxapp.register'),
        ),
    ]
