# Generated by Django 4.0 on 2023-12-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0051_alter_vaccine_record_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax3',
            field=models.IntegerField(default=0),
        ),
    ]
