# Generated by Django 4.0 on 2023-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0054_alter_schedule_vax1_alter_schedule_vax2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='vax1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vax2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vax3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='vax3',
            field=models.IntegerField(null=True),
        ),
    ]
