# Generated by Django 4.0 on 2023-12-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0055_alter_schedule_vax1_alter_schedule_vax2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='child',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
