# Generated by Django 4.0 on 2023-12-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0056_alter_vaccine_record_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaxapp.register'),
        ),
    ]
