# Generated by Django 4.0 on 2024-01-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0058_alter_barangay_healthworker_alter_register_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine_record',
            name='Vaccinator',
            field=models.TextField(null=True),
        ),
    ]
