# Generated by Django 4.0 on 2024-01-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0065_alter_admin_record_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_record',
            name='added_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin_record',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin_record',
            name='child_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin_record',
            name='date_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin_record',
            name='father_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin_record',
            name='mother_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin_record',
            name='place_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
