# Generated by Django 4.0 on 2024-01-03 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0066_alter_admin_record_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_record',
            name='child',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.register'),
        ),
    ]
