# Generated by Django 4.0 on 2024-01-03 05:57

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0070_alter_admin_record_child_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_record',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='vaxapp.register'),
        ),
    ]
