# Generated by Django 4.0 on 2024-01-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0078_alter_vaccine_record_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.register'),
        ),
    ]
