# Generated by Django 4.0 on 2024-01-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0079_alter_schedule_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_record',
            name='child_record',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.vaccine_record'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.register'),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.register'),
        ),
    ]
