# Generated by Django 4.0 on 2024-01-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vaxapp', '0080_alter_admin_record_child_record_alter_schedule_child_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_record',
            old_name='child',
            new_name='child_id',
        ),
        migrations.AlterField(
            model_name='admin_record',
            name='child_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.vaccine_record'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.register'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='vaccine_record',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.register'),
        ),
    ]
